#pragma once

char *CentralEuropeanEncoding[] {
    ".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",
    ".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",
    ".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",".notdef",
    ".notdef",".notdef","space","exclam","quotedbl","numbersign","dollar","percent","ampersand","quotesingle",
    "parenleft","parenright","asterisk","plus","comma","hyphen","period","slash","zero","one",
    "two","three","four","five","six","seven","eight","nine","colon","semicolon",
    "less","equal","greater","question","at","A","B","C","D","E",
    "F","G","H","I","J","K","L","M","N","O",
    "P","Q","R","S","T","U","V","W","X","Y",
    "Z","bracketleft","backslash","bracketright","asciicircum","underscore","grave","a","b","c",
    "d","e","f","g","h","i","j","k","l","m",
    "n","o","p","q","r","s","t","u","v","w",
    "x","y","z","braceleft","bar","braceright","asciitilde",".notdef",".notdef",".notdef",
    "quotesinglbase",".notdef","quotedblbase","ellipsis","dagger","daggerdbl",".notdef","perthousand","Scaron","guilsinglleft",
    "Sacute","Tcaron1","Zcaron","Zacute",".notdef","quoteleft","quoteright","quotedblleft","quotedblright","bullet",
    "endash","emdash",".notdef","trademark","scaron","guilsinglright","sacute","tcaron1","zcaron","zacute",
    ".notdef","caron","breve","Lslash","currency","Aogonek1","brokenbar","section","dieresis","copyright",
    "Scommaaccent","guillemotleft","logicalnot",".notdef","registered","Zdotaccent","degree","plusminus","ogonek","lslash",
    "acute","mu","paragraph","periodcentered","cedilla","aogonek1","scommaaccent","guillemotright","Lcaron1","hungarumlaut",
    "lcaron1","zdotaccent","Racute","Aacute","Acircumflex","Abreve","Adieresis","Lacute","Cacute","Ccedilla",
    "Ccaron1","Eacute","Eogonek1","Edieresis","Ecaron1","Iacute","Icircumflex","Dcaron1","Dcroat","Nacute",
    "Ncaron1","Oacute","Ocircumflex","Ohungarumlaut","Odieresis","multiply","Rcaron1","Uring","Uacute","Uhungarumlaut",
    "Udieresis","Yacute","Tcommaaccent","germandbls","racute","aacute","acircumflex","abreve","adieresis","lacute",
    "cacute","ccedilla","ccaron1","eacute","eogonek1","edieresis","ecaron1","iacute","icircumflex","dcaron1",
    "dcroat","nacute","ncaron1","oacute","ocircumflex","ohungarumlaut","odieresis","divide","rcaron1","uring",
    "uacute","uhungarumlaut","udieresis","yacute","tcommaaccent","dotaccent"};
